name: test-image

on:
    workflow_run:
        workflows:
            - Docker
        branches:
            - master
        types:
            - completed

jobs:
    test-image:
        name: Test image
        runs-on: ubuntu-latest
        container: ubuntu:latest
        services:
            ansible-node:
                image: ghcr.io/pgulb/rocky-ansible-tester:master
                volumes:
                    - /sys/fs/cgroup:/sys/fs/cgroup:rw
                options: --privileged --cgroupns=host
        steps:
            - name: install packages
              run: apt-get update; apt-get install netcat-openbsd sshpass openssh-client -y
            - name: test sshd with netcat
              run: nc -vz ansible-node 22
            - name: test sshd with ssh
              run: sshpass -p '123' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@ansible-node ls -ltra
