name: test-image

on:
    workflow_run:
        workflows:
            - Docker
        branches:
            - master
        types:
            - completed

jobs:
    test-image:
        name: Test image
        runs-on: ubuntu-latest
        services:
            ansible-node:
                image: ghcr.io/pgulb/rocky-ansible-tester:master
                volumes:
                    - /sys/fs/cgroup:/sys/fs/cgroup:rw
                options: --privileged --cgroupns=host
                ports:
                    - 2222:22
        steps:
            - name: install packages
              run: sudo apt-get install netcat sshpass openssh-client -y
            - name: test sshd with netcat
              run: nc -vz localhost 2222
            - name: test sshd with ssh
              run: sshpass -p '123' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 root@localhost ls -ltra
